name: 'Terraform'

on:
  workflow_call:
    inputs:
      instance_name:
        required: true
        type: string
      subdomain:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY_ID:
        required: true
  workflow_dispatch:
    inputs:
      instance_name:
        required: true
        type: string
      subdomain:
        required: true
        type: string
  issues:
    type:
      -opened

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region:  ${{ secrets.AWS_REGION }}

    - name: Run Terraform
      run: |
        cd aws/ec2_instance
        terraform init
        terraform apply -auto-approve -var="intance_name=${{ inputs.intance_name }}" -var="subdomain=${{ inputs.subdomain }}" 
