name: 'S3 Bucket'

on:
  issues:
    type:
      -opened

jobs:
  terraform_apply:
    if: ${{ github.event.label.name == 'invalid' }}
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region:  ${{ secrets.AWS_REGION }}

    - name: Extract Bucket Name from Issue
      run: |
        export BUCKET_NAME=$(echo "${{ github.event.issue.title }}")
        echo "Bucket Name: $BUCKET_NAME"
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Run Terraform
      run: |
        cd aws/s3_bucket
        terraform init
        terraform apply -auto-approve -var="bucket_name=${{ env.BUCKET_NAME }}"
    
    - name: Save Terraform Files to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
        aws_bucket: static-site-${{ env.BUCKET_NAME }}
        source_dir: aws/s3_bucket/

  terraform_destroy:
    if: ${{ github.event.label.name == 'bug' }}
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Extract Bucket Name from Issue
      run: |
        export BUCKET_NAME=$(echo "${{ github.event.issue.title }}")
        echo "Bucket Name: $BUCKET_NAME"
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Download Terraform Files from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://static-site-${{ env.BUCKET_NAME }}/
        destination: aws/s3_bucket/
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws_region: ${{ secrets.AWS_REGION }}
      run: ls -la aws/s3_bucket/

    - name: Run Terraform Destroy
      run: |
        cd aws/s3_bucket/
        terraform destroy -auto-approve
