name: 'Terraform'

on:
  issues:
    type:
      -opened

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region:  ${{ secrets.AWS_REGION }}

    - name: Extract Bucket Name from Issue
      run: |
        export BUCKET_NAME=$(echo "${{ github.event.issue.title }}")
        echo "Bucket Name: $BUCKET_NAME"
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Run Terraform
      run: |
        cd terraform/s3_bucket
        terraform init
        terraform apply -auto-approve -var="bucket_name=${{ env.BUCKET_NAME }}"
